### ISSUE TITLE
Self Service 0.3.2 Not Updated On Nexus

### ISSUE THREAD

**Issue by MoralTruth** [Jarvie8176/StardewMods#4]
On the SMAPI console, it said that I can update one mod, which was Self Service 0.3.2. When I got to the [URL for the mod](https://www.nexusmods.com/stardewvalley/mods/1304/?tab=files), it said that 0.3.2 was last uploaded on 29 Jun 2018, 10:51pm. Therefore, it hasn't been updated yet.

Not necessarily a bug, but just thought I would report this.

**Comment by Jarvie8176** [comment]
https://github.com/Jarvie8176/StardewMods/pull/6
